### ISSUE TITLE
Long running queries do not appear to return

### ISSUE THREAD

**Issue by dparnell** [orthecreedence/cl-rethinkdb#26]
Hi,

  I've been having trouble with this rethinkdb driver.  When I try to execute a complex query I get no results  :scream: :

```lisp
(let ((result :no-value))
	(as:with-event-loop (:catch-app-errors t)
       (bb:chain
   	(bb:alet* ((sock (r:connect "localhost" 38015 :db "crunchbase"))
                   (x (print "HERE"))
                   (query (r:r (:count (:filter (:table "profiles") 
                                                (r:fn (profile) (:== (:attr profile "region") "New York"))))))
                   (y (print "THERE"))
                   (value (r:run sock query))
                   (z (print "WHERE")))
                  (print (list x y z))
                  (setf result value)
                  (r:disconnect sock))
        (:catch (e) (progn (format t "Error: ~A" e) (setf result e)))
        (:finally (print "That's all folks"))))
  result)
```

This prints out the following:

    "HERE" 
    "THERE"

and returns ```:no-value```

If I remove the filter as follows I see the expected result:

````lisp
(let ((result :no-value))
  (as:with-event-loop (:catch-app-errors t)
    (bb:chain
     (bb:alet* ((sock (r:connect "localhost" 38015 :db "crunchbase"))
                (x (print "HERE"))
                (query (r:r (:count (:table "profiles"))))
                (y (print "THERE"))
                (value (r:run sock query))
                (z (print "WHERE")))
               (print (list x y z))
               (setf result value)
               (r:disconnect sock))
     (:catch (e) (progn (format t "Error: ~A" e) (setf result e)))
     (:finally (print "That's all folks"))))
  
  result)
```

This prints as expected:

    "HERE" 
    "THERE" 
    "WHERE" 
    ("HERE" "THERE" "WHERE") 
    "That's all folks" 

and returns a nice number containing the count of the rows.

I am hoping that I am just doing something silly.  If you need any more information let me know.  I can organise for you to have access to the rethinkdb database if that would help.

Thanks for all your great work :)

**Comment by dparnell** [comment]
On further investigation it appears that specifying the ```:read-timeout``` option in the ```r:connect``` allows my query to run, however I have yet been unable to figure out how to catch this timeout.

**Comment by orthecreedence** [comment]
The timeout not being triggered on the promise is definitely a bug, I will look into that!

Also, the [v1.15.x](https://github.com/orthecreedence/cl-rethinkdb/tree/v1.15.x) branch is releasing soon, which has a number of fixes/rewrites, so give that a shot as well if you have a minute. It will probably be merging in sometime this week.

**Comment by dparnell** [comment]
Thanks.  I look forward to giving the new branch a go.  One thing I also noticed was that unless I patch the ```cl-async-util:error-str``` function my sbcl instance would crash due to an unknown error code (-110) triggering an assertion in ```libuv```.  This is using a version of ```libuv``` build via homebrew under Mac OS X 10.10.

**Comment by orthecreedence** [comment]
You're not alone here, libuv seems to spawn a lot of error codes through that it doesn't map and it has the really obnoxious behavior of crashing when it encounters one. 

I think this could be an easy fix, I'll try to get that working tonight (added https://github.com/orthecreedence/cl-async/issues/118).

**Comment by orthecreedence** [comment]
The uv error code assertions should be gone now, BTW.

**Comment by orthecreedence** [comment]
The v1.16.x branch was just merged into master, can you check and make sure this issue is resolved?

**Comment by dparnell** [comment]
I've tried our app with the latest code and after fixing a couple of things everything seems to be working.  I'll be submitting a pull request soon with my changes.
