### ISSUE TITLE
:branch call has logic reversed

### ISSUE THREAD

**Issue by omasri** [orthecreedence/cl-rethinkdb#27]
Per the documentation the logic should be (:branch (condition) (on-true...) (on-false ...))
however, it is executing as (:branch (condition) (on-false...) (on-true ...))

**Comment by orthecreedence** [comment]
Would you mind trying on the [v1.15.x branch](https://github.com/orthecreedence/cl-rethinkdb/tree/v1.15.x)? I think this may be fixed. Most of the driver has been rebuilt, and I'd be surprised if this was still a problem.

**Comment by omasri** [comment]
Thanks. Will let you know.
