### ISSUE TITLE
get-all not working with compound indexes

### ISSUE THREAD

**Issue by omasri** [orthecreedence/cl-rethinkdb#28]
Hi,

I can create a compound index, but the get-all is not returning the correct values.   the get-all via a python command on the server works. Am I doing something wrong with how I pass in the key value list?

;
; CREATE INDEX
;
(...(:index-create (:table "cities") 
                   "citiesndx2"
                   :function (r:fn (profile) (list (:attr profile "Region") (:attr profile "City"))))))

;
; TEST VIA PYTHON ON SERVER
;  This works
>> con = r.connect("localhost", 28015).repl()
>>> t = r.rb("crunchbase").table("cities")
>>> t.get_all(["05","copainala"],index="citiesndx2").count().run(con)
1

;
; TEST VIA LISP 
; No Results 
(..... (:get-all (:table "cities") (list "05" "copainala") :index "citiesndx2")))

**Comment by orthecreedence** [comment]
`get-all` takes a *list* of index values (in an actual list, not in &rest form). It's set up this way because it's really hard for CL to support both &rest and &key (which get-all uses), so it replaces the &rest part with an actual list.

I *think* doing
```lisp
(..... (:get-all (:table "cities") (list (list "05" "copainala")) :index "citiesndx2")))
```
may solve your problem.

Can you confirm?

**Comment by omasri** [comment]
Thanks. That worked.  Issue solved.
