### ISSUE TITLE
authenication?

### ISSUE THREAD

**Issue by sjatkins2** [orthecreedence/cl-rethinkdb#30]
I didn't see anything about to authenticate a connection to the database.  Did I miss it?  I don't run databases without auth for even a modest production system.

**Comment by orthecreedence** [comment]
I don't think you missed anything, I haven't put much time into auth *at all*. There's a big update coming soon (1.15.x) which includes a major rewrite of a lot of stuff, and I'll try to fit auth into there before it merges in. This may be sometime in the next week or two.

Thanks for bringing this up!

**Comment by orthecreedence** [comment]
Apparently the driver had working auth for a while, and I just don't remember building it (and stupidly never documented it).

```lisp
(r:connect "127.0.0.1" 28015 :auth "mykey123")
```

Updating docs now...
