### ISSUE TITLE
What is the sha before 1.15 was merged to master?

### ISSUE THREAD

**Issue by nightshade427** [orthecreedence/cl-rethinkdb#34]
What is the sha before 1.15 was merged to master? I still need to use the old branch for little while.

**Comment by orthecreedence** [comment]
Hey, sorry this one slipped through the cracks. I (stupidly) never tagged the pre-v1.15 merge, so I'm not entirely sure what the commit was =[.

Also, just a heads up, last night I converted the driver to use the v2.0.x protocol: https://github.com/orthecreedence/cl-rethinkdb/issues/37 (there are some good upgrade/usage notes here). This has been merged into master, so maybe make a note of your current commit if you don't want to upgrade on the next QL release.

**Comment by nightshade427** [comment]
In using 2.0 as we speak. Thanks :)
