### ISSUE TITLE
each not working with ungroup

### ISSUE THREAD

**Issue by omasri** [orthecreedence/cl-rethinkdb#35]
Trying to use the each function on the results of a group/ungroup, and it is not working right.

NOTE: we have a wrapper around the libs r async calls. This is more a question if you have managed to get each to work with the results of a group

The each on a read of a table works as expected.  the var spits out the last read value

        (let ((var nil))
        (rdb:with-connection
          (rdb:each 
           (:limit (:table "actions") 10)   as therow  
           do (setf var therow))) var)

but when I :group and :ungroup the table it seems that the each doesn't actually loop

     (let ((var nil))
     (rdb:with-connection
       (rdb:each 
           (:ungroup (:group (:limit (:table "actions") 10) "Staff"))
       as therow
       do (setf var therow))) var)

the group query returns data like 

          (rdb:with-connection
            (rdb:query  (:ungroup (:group (:limit (:table "actions") 10) "Staff")) ))

example

        {
        group"KLY"
        reduction[  {..} {..} ]
        }
        {
        group"XXY"
        reduction[  {..} {..} ]
        }

**Comment by omasri** [comment]
forgot

**Comment by orthecreedence** [comment]
What version of RethinkDB are you running, and would you mind trying the cl-rethinkdb v1.16.x branch?

**Comment by orthecreedence** [comment]
Scratch that, please try the master branch as is was just upgraded to 2.0.x.
