### ISSUE TITLE
:expr is in docs but does not exist

### ISSUE THREAD

**Issue by gitwn** [orthecreedence/cl-rethinkdb#36]
I have grepped the source tree and can't find ```:expr``` even though readme states that
```expr (lisp-object) => RethinkDB object```

**Comment by orthecreedence** [comment]
Yep, you're right, pushing a fix for this later tonight.

**Comment by orthecreedence** [comment]
Ok, should be in there now. Sorry about the delay. Ended up merging the v1.16.x branch into master, so if you're using RDB >= 1.16 you should get all the new features.

Going to be working on the v2 updates very shortly as well (along with changefeeds https://github.com/orthecreedence/cl-rethinkdb/issues/37).
