### ISSUE TITLE
Performance when lots of data returned

### ISSUE THREAD

**Issue by nightshade427** [orthecreedence/cl-rethinkdb#39]
When I get a lot lot of data from rethink 30+% of the app time is spent processing json from yason that came from cl-rethinkdb reponses.

```
 3.089 |      0.037 |  72,184,528 |     74,170 |   0.000042 | YASON::PARSE-STRING 
```

```
------------------------------------------------------------------------                                                                        
   589  31.0                   CL-RETHINKDB::JSON-TO-RESPONSE [265]                                                                             
     1   0.1                   YASON:PARSE [170]                                                                                                
   569  29.9                   YASON::%PARSE-ARRAY [546]                                                                                        
   536  28.2                   YASON::PARSE-OBJECT [171]                                                                                        
     2   0.1    589  31.0   YASON:PARSE [170]  
```

Seems to mostly be coming from rethinkdb.

Can we maybe use a different faster json parsing library? Maybe https://github.com/Rudolph-Miller/jonathan. according to https://sites.google.com/site/sabraonthehill/home/json-libraries it is very fast. It also shows that yason isnt fairly slow.

Thoughts?

**Comment by nightshade427** [comment]
I have a fork Im using now that uses jonathan and shows 2-3x speed up.

https://github.com/nightshade427/cl-rethinkdb/commit/a46fe27c318dd7fa80d4967e3551b2bdf237b6a2

**Comment by orthecreedence** [comment]
Hey, merged in your changes to the latest master. Should be faster now =]

**Comment by nightshade427** [comment]
This is great! Thanks!
