### ISSUE TITLE
queries that return data that are rethinkdb times are not times in lisp

### ISSUE THREAD

**Issue by nightshade427** [orthecreedence/cl-rethinkdb#41]
How can I use reql::now and get records back that have time values I can easily use? 

When using reql::now to insert a time into a record when saving, then grabing that record back, the time is not a universal-time or in format that decode-universal-time can understand. 

Thoughts?

**Comment by orthecreedence** [comment]
I'm actually not even sure what it returns right now (at work so can't test it). There's a function in `reql/pseudotypes.lisp` called convert-pseudotypes that would be the prime place to convert this (under the `:epoch` case). If you want to take a crack at it, be my guest, or I can take a look in the next few days. Good catch!

**Comment by nightshade427** [comment]
It returns ```epoch_time":1434566254.2369999886```

So did something like this:
```(local-time:unix-to-timestamp (floor time-from-cl-rethink))```

**Comment by nightshade427** [comment]
https://github.com/orthecreedence/cl-rethinkdb/pull/42

**Comment by orthecreedence** [comment]
I think since it encodes to a local-time:timestamp with (by default) UTC, we don't have to worry about timezones. If a user wants it to encode properly to their zone, they can change `local-time:*default-timezone*` and it will encode properly. So the change works great as-is.
