### ISSUE TITLE
Undefined state in wait-complete

### ISSUE THREAD

**Issue by gtod** [orthecreedence/cl-rethinkdb#50]
I compiled in verbose mode and found that the `state` in this `with-query` macro invocation is not defined.  No idea what the consequences might be but just FYI.

https://github.com/orthecreedence/cl-rethinkdb/blob/master/query.lisp#L316

**Comment by orthecreedence** [comment]
Thanks, this should fix it: https://github.com/orthecreedence/cl-rethinkdb/commit/f435e72dce7f900f599ade193859a202fd1ac33e
